[package]
name = "blockworld-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
bytemuck = {version = "1.14.1",features = ["derive"]}
env_logger = "0.11.0"
glam = "0.25.0"
image = "0.24.8"
log = "0.4.20"
pollster = "0.3.0"
wgpu = "0.19.1"
winit = "0.29.10"
winit_input_helper = "0.15.3"

[build-dependencies]
anyhow = "1.0.79"
fs_extra = "1.2"
glob = "0.3"

[lints.rust]
unused = "allow"